import type { NewsSourceCatalogSnapshot } from "./news-source-catalog.js";

const reviewedAt = "2026-08-04T00:00:00.000Z";

export const initialNewsSourceCatalogSnapshot = {
  schemaVersion: 1,
  sources: [
    {
      source: {
        id: "10000000-0000-4000-8000-000000000001",
        name: "Pagina/12",
        orientation: "izquierda",
        type: "media",
        region: "argentina",
        country: "AR",
        language: "es-ar",
        active: true,
        approvalStatus: "approved",
        reviewedAt,
      },
      discovery: {
        mode: "rss",
        feedUrl:
          "https://www.pagina12.com.ar/arc/outboundfeeds/rss/secciones/el-pais/notas",
        domains: ["pagina12.com.ar"],
      },
    },
    {
      source: {
        id: "10000000-0000-4000-8000-000000000002",
        name: "El Destape",
        orientation: "centroizquierda",
        type: "media",
        region: "argentina",
        country: "AR",
        language: "es-ar",
        active: true,
        approvalStatus: "approved",
        reviewedAt,
      },
      discovery: { mode: "search_only", domains: ["eldestaperadio.com"] },
    },
    {
      source: {
        id: "10000000-0000-4000-8000-000000000003",
        name: "Perfil",
        orientation: "centro",
        type: "media",
        region: "argentina",
        country: "AR",
        language: "es-ar",
        active: true,
        approvalStatus: "approved",
        reviewedAt,
      },
      discovery: { mode: "search_only", domains: ["perfil.com"] },
    },
    {
      source: {
        id: "10000000-0000-4000-8000-000000000004",
        name: "La Nacion",
        orientation: "centroderecha",
        type: "media",
        region: "argentina",
        country: "AR",
        language: "es-ar",
        active: true,
        approvalStatus: "approved",
        reviewedAt,
      },
      discovery: { mode: "search_only", domains: ["lanacion.com.ar"] },
    },
    {
      source: {
        id: "10000000-0000-4000-8000-000000000005",
        name: "La Derecha Diario",
        orientation: "derecha",
        type: "media",
        region: "argentina",
        country: "AR",
        language: "es-ar",
        active: true,
        approvalStatus: "approved",
        reviewedAt,
      },
      discovery: { mode: "search_only", domains: ["laderechadiario.com"] },
    },
    {
      source: {
        id: "20000000-0000-4000-8000-000000000001",
        name: "Reuters",
        orientation: "sin_clasificar",
        type: "agency",
        region: "international",
        country: "GB",
        language: "en",
        active: true,
        approvalStatus: "approved",
        reviewedAt,
      },
      discovery: { mode: "search_only", domains: ["reuters.com"] },
    },
    {
      source: {
        id: "20000000-0000-4000-8000-000000000002",
        name: "Associated Press",
        orientation: "sin_clasificar",
        type: "agency",
        region: "international",
        country: "US",
        language: "en",
        active: true,
        approvalStatus: "approved",
        reviewedAt,
      },
      discovery: { mode: "search_only", domains: ["apnews.com"] },
    },
    {
      source: {
        id: "20000000-0000-4000-8000-000000000003",
        name: "Agence France-Presse",
        orientation: "sin_clasificar",
        type: "agency",
        region: "international",
        country: "FR",
        language: "fr",
        active: true,
        approvalStatus: "approved",
        reviewedAt,
      },
      discovery: { mode: "search_only", domains: ["afp.com"] },
    },
    {
      source: {
        id: "20000000-0000-4000-8000-000000000004",
        name: "BBC Mundo",
        orientation: "sin_clasificar",
        type: "media",
        region: "international",
        country: "GB",
        language: "es",
        active: true,
        approvalStatus: "approved",
        reviewedAt,
      },
      discovery: {
        mode: "rss",
        feedUrl: "https://feeds.bbci.co.uk/mundo/rss.xml",
        domains: ["bbc.com", "bbc.co.uk"],
      },
    },
  ],
} satisfies NewsSourceCatalogSnapshot;
